[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_fusion_solana = "5gJMGxawUbdqfRpdVKj1eJrPfgMQ1Rrroa5WEoidLWQU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/briankasper/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "dumped-programs/metaplex.so"